name: "Test"

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        luaVersion: ["5.1", "5.2", "5.3", "5.4", "luajit-2.1.0-beta3", "luajit-openresty"]

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true

    - uses: leafo/gh-actions-lua@v8
      with:
        luaVersion: ${{ matrix.luaVersion }}

    - uses: leafo/gh-actions-luarocks@v4

    - name: dependencies
      run: |
        luarocks install busted
        luarocks install luacov-coveralls

    - name: Execute tests
      run: |
        make test LUA_VER=""

    - name: Report test coverage
      if: success()
      continue-on-error: true
      run: luacov-coveralls
      env:
        COVERALLS_REPO_TOKEN: ${{ github.token }}